% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\title{Data Quality Report: Comparison of ship and ship}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{No time restriction. All available data were analysed}
\author{(c) Universitätsklinikum Erlangen}
\date{\today}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Data Quality Report: Comparison of ship and ship},
  pdfauthor={(c) Universitätsklinikum Erlangen},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[left=2.5cm,right=2.5cm,top=2cm,bottom=2cm]{geometry}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
% MIRACUM DQA-Tool (i2b2)
% Copyright (C) 2019-2021 Universitätsklinikum Erlangen
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.

\usepackage{titling}
\usepackage{caption}
\captionsetup[figure]{labelformat=empty}
\usepackage[ngerman]{babel}
\usepackage{graphicx}
\usepackage{float}
\usepackage{pdflscape}
\usepackage{longtable}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\newpage

\hypertarget{data-map}{%
\section{Data Map}\label{data-map}}

\hypertarget{target-data-system}{%
\subsection{Target Data System}\label{target-data-system}}

There is no data to display.

\hypertarget{source-data-system}{%
\subsection{Source Data System}\label{source-data-system}}

There is no data to display.

\newpage

\hypertarget{completeness-checks}{%
\section{Completeness Checks}\label{completeness-checks}}

\hypertarget{validation}{%
\subsection{Validation}\label{validation}}

Completeness checks (validation) evaluate the ETL (extract transform
load) jobs. They compare for each variable the exact matching of the
number of distinct values, the number of valid values (=n), and the
number of missing values between the source data system and the target
data system.

\begin{table}[H]
\centering
\begin{tabular}{l|l|l|l}
\hline
\textbf{Variable} & \textbf{Check Distincts} & \textbf{Check Valids} & \textbf{Check Missings}\\
\hline
age & passed & passed & passed\\
\hline
cholesterol & passed & passed & passed\\
\hline
contraception & passed & passed & passed\\
\hline
dbp1 & passed & passed & passed\\
\hline
dbp2 & passed & passed & passed\\
\hline
dev\_bp & passed & passed & passed\\
\hline
dev\_length & passed & passed & passed\\
\hline
dev\_weight & passed & passed & passed\\
\hline
diab\_age & passed & passed & passed\\
\hline
diab\_known & passed & passed & passed\\
\hline
exdate & passed & passed & passed\\
\hline
family & passed & passed & passed\\
\hline
hdl & passed & passed & passed\\
\hline
height & passed & passed & passed\\
\hline
id & passed & passed & passed\\
\hline
income & passed & passed & passed\\
\hline
ldl & passed & passed & passed\\
\hline
myocard & passed & passed & passed\\
\hline
obs\_bp & passed & passed & passed\\
\hline
obs\_int & passed & passed & passed\\
\hline
obs\_soma & passed & passed & passed\\
\hline
sbp1 & passed & passed & passed\\
\hline
sbp2 & passed & passed & passed\\
\hline
school & passed & passed & passed\\
\hline
sex & passed & passed & passed\\
\hline
smoking & passed & passed & passed\\
\hline
stroke & passed & passed & passed\\
\hline
waist & passed & passed & passed\\
\hline
weight & passed & passed & passed\\
\hline
\end{tabular}
\end{table}

\hypertarget{verification}{%
\subsection{Verification}\label{verification}}

\begin{table}[H]
\centering
\begin{tabular}{l|l|l}
\hline
\textbf{Variable} & \textbf{Missings [\%] (source)} & \textbf{Missings [\%] (target)}\\
\hline
age & 0 & 0\\
\hline
cholesterol & 0.7 & 0.7\\
\hline
contraception & 0 & 0\\
\hline
dbp1 & 0.09 & 0.09\\
\hline
dbp2 & 0.28 & 0.28\\
\hline
dev\_bp & 0 & 0\\
\hline
dev\_length & 0 & 0\\
\hline
dev\_weight & 0 & 0\\
\hline
diab\_age & 0 & 0\\
\hline
diab\_known & 0 & 0\\
\hline
exdate & 0 & 0\\
\hline
family & 0 & 0\\
\hline
hdl & 0.74 & 0.74\\
\hline
height & 0.14 & 0.14\\
\hline
id & 0 & 0\\
\hline
income & 0 & 0\\
\hline
ldl & 1.3 & 1.3\\
\hline
myocard & 0 & 0\\
\hline
obs\_bp & 0 & 0\\
\hline
obs\_int & 0 & 0\\
\hline
obs\_soma & 0 & 0\\
\hline
sbp1 & 0.09 & 0.09\\
\hline
sbp2 & 0.28 & 0.28\\
\hline
school & 0 & 0\\
\hline
sex & 0 & 0\\
\hline
smoking & 0 & 0\\
\hline
stroke & 0 & 0\\
\hline
waist & 0.28 & 0.28\\
\hline
weight & 0.19 & 0.19\\
\hline
\end{tabular}
\end{table}

\newpage

\hypertarget{conformance-checks}{%
\section{Conformance Checks}\label{conformance-checks}}

\hypertarget{value-conformance}{%
\subsection{Value Conformance}\label{value-conformance}}

Value conformance checks (verification) compare for each variable the
values of each data system to predefined constraints. Those constraints
can be defined for each variable and data system individually in the
metadata repository (MDR).

\begin{table}[H]
\centering
\begin{tabular}{l|l|l}
\hline
\textbf{Variable} & \textbf{Check Source Data} & \textbf{Check Target Data}\\
\hline
age & failed & failed\\
\hline
cholesterol & passed & passed\\
\hline
contraception & failed & failed\\
\hline
dbp1 & failed & failed\\
\hline
dbp2 & passed & passed\\
\hline
dev\_bp & failed & failed\\
\hline
dev\_length & failed & failed\\
\hline
dev\_weight & failed & failed\\
\hline
diab\_known & failed & failed\\
\hline
exdate & passed & passed\\
\hline
family & failed & failed\\
\hline
hdl & passed & passed\\
\hline
height & passed & passed\\
\hline
id & passed & passed\\
\hline
income & failed & failed\\
\hline
ldl & passed & passed\\
\hline
myocard & failed & failed\\
\hline
obs\_bp & failed & failed\\
\hline
obs\_int & failed & failed\\
\hline
obs\_soma & failed & failed\\
\hline
sbp1 & failed & failed\\
\hline
sbp2 & failed & failed\\
\hline
school & failed & failed\\
\hline
sex & passed & passed\\
\hline
smoking & failed & failed\\
\hline
stroke & failed & failed\\
\hline
waist & passed & passed\\
\hline
weight & passed & passed\\
\hline
a\_present\_and\_b\_vv & failed & failed\\
\hline
a\_present\_and\_b\_levels\_vl & failed & failed\\
\hline
\end{tabular}
\end{table}

\newpage

\hypertarget{detailed-descriptive-analysis}{%
\section{Detailed Descriptive
Analysis}\label{detailed-descriptive-analysis}}

\hypertarget{age}{%
\subsection{age}\label{age}}

Description for dataelement `age'

\hypertarget{representation-in-source-data-system}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system}}

\begin{itemize}
\tightlist
\item
  Variable: age
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: age
\item
  Variable type: integer

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 64
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 49.86\\
\hline
Minimum & 19\\
\hline
Median & 50\\
\hline
Maximum & 82\\
\hline
SD & 16.19\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2154\\
\hline
OutLo & 0\\
\hline
OutHi & 0\\
\hline
Variance & 261.95\\
\hline
Range & 63\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|l}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  20 & Inf\\
  \hline
  \end{tabular}
  \end{table}
\item
  Extrem values are not conform with constraints.
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system}}

\begin{itemize}
\tightlist
\item
  Variable: age
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: age
\item
  Variable type: integer

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 64
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 49.86\\
\hline
Minimum & 19\\
\hline
Median & 50\\
\hline
Maximum & 82\\
\hline
SD & 16.19\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2154\\
\hline
OutLo & 0\\
\hline
OutHi & 0\\
\hline
Variance & 261.95\\
\hline
Range & 63\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|l}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  20 & Inf\\
  \hline
  \end{tabular}
  \end{table}
\item
  Extrem values are not conform with constraints.
\end{itemize}

\newpage

\hypertarget{cholesterol}{%
\subsection{cholesterol}\label{cholesterol}}

Description for dataelement `cholesterol'

\hypertarget{representation-in-source-data-system-1}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-1}}

\begin{itemize}
\tightlist
\item
  Variable: cholesterol
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: cholesterol
\item
  Variable type: float

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2139
  \item
    Missing values: 15
  \item
    Distinct values: 1668
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 5.76\\
\hline
Minimum & 2.67\\
\hline
Median & 5.68\\
\hline
Maximum & 12.12\\
\hline
SD & 1.2\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2139\\
\hline
OutLo & 0\\
\hline
OutHi & 23\\
\hline
Variance & 1.43\\
\hline
Range & 9.45\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|l}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  0 & Inf\\
  \hline
  \end{tabular}
  \end{table}
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-1}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-1}}

\begin{itemize}
\tightlist
\item
  Variable: cholesterol
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: cholesterol
\item
  Variable type: float

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2139
  \item
    Missing values: 15
  \item
    Distinct values: 1668
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 5.76\\
\hline
Minimum & 2.67\\
\hline
Median & 5.68\\
\hline
Maximum & 12.12\\
\hline
SD & 1.2\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2139\\
\hline
OutLo & 0\\
\hline
OutHi & 23\\
\hline
Variance & 1.43\\
\hline
Range & 9.45\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|l}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  0 & Inf\\
  \hline
  \end{tabular}
  \end{table}
\end{itemize}

\newpage

\hypertarget{contraception}{%
\subsection{contraception}\label{contraception}}

Description for dataelement `contraception':

1 = yes; 2 = no

\hypertarget{representation-in-source-data-system-2}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-2}}

\begin{itemize}
\tightlist
\item
  Variable: contraception
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: contraception
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 4
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{contraception} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
99801 & 1264 & 58.682\\
\hline
1 & 584 & 27.112\\
\hline
2 & 302 & 14.020\\
\hline
99900 & 4 & 0.186\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2 '
\item
  Levels that are not conform with the value set:\\
  99801\\
  99900
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-2}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-2}}

\begin{itemize}
\tightlist
\item
  Variable: contraception
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: contraception
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 4
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{contraception} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
99801 & 1264 & 58.682\\
\hline
1 & 584 & 27.112\\
\hline
2 & 302 & 14.020\\
\hline
99900 & 4 & 0.186\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2 '
\item
  Levels that are not conform with the value set:\\
  99801\\
  99900
\end{itemize}

\newpage

\hypertarget{dbp1}{%
\subsection{dbp1}\label{dbp1}}

Description for dataelement `dbp1'

\hypertarget{representation-in-source-data-system-3}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-3}}

\begin{itemize}
\tightlist
\item
  Variable: dbp1
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: dbp1
\item
  Variable type: integer

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2152
  \item
    Missing values: 2
  \item
    Distinct values: 75
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 84.52\\
\hline
Minimum & 53\\
\hline
Median & 84\\
\hline
Maximum & 198\\
\hline
SD & 11.81\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2152\\
\hline
OutLo & 0\\
\hline
OutHi & 17\\
\hline
Variance & 139.52\\
\hline
Range & 145\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|r}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  40 & 160\\
  \hline
  \end{tabular}
  \end{table}
\item
  Extrem values are not conform with constraints.
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-3}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-3}}

\begin{itemize}
\tightlist
\item
  Variable: dbp1
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: dbp1
\item
  Variable type: integer

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2152
  \item
    Missing values: 2
  \item
    Distinct values: 75
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 84.52\\
\hline
Minimum & 53\\
\hline
Median & 84\\
\hline
Maximum & 198\\
\hline
SD & 11.81\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2152\\
\hline
OutLo & 0\\
\hline
OutHi & 17\\
\hline
Variance & 139.52\\
\hline
Range & 145\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|r}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  40 & 160\\
  \hline
  \end{tabular}
  \end{table}
\item
  Extrem values are not conform with constraints.
\end{itemize}

\newpage

\hypertarget{dbp2}{%
\subsection{dbp2}\label{dbp2}}

Description for dataelement `dbp2'

\hypertarget{representation-in-source-data-system-4}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-4}}

\begin{itemize}
\tightlist
\item
  Variable: dbp2
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: dbp2
\item
  Variable type: integer

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2148
  \item
    Missing values: 6
  \item
    Distinct values: 71
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 83.52\\
\hline
Minimum & 55\\
\hline
Median & 83\\
\hline
Maximum & 151\\
\hline
SD & 11.52\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2148\\
\hline
OutLo & 0\\
\hline
OutHi & 17\\
\hline
Variance & 132.67\\
\hline
Range & 96\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|r}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  40 & 160\\
  \hline
  \end{tabular}
  \end{table}
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-4}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-4}}

\begin{itemize}
\tightlist
\item
  Variable: dbp2
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: dbp2
\item
  Variable type: integer

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2148
  \item
    Missing values: 6
  \item
    Distinct values: 71
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 83.52\\
\hline
Minimum & 55\\
\hline
Median & 83\\
\hline
Maximum & 151\\
\hline
SD & 11.52\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2148\\
\hline
OutLo & 0\\
\hline
OutHi & 17\\
\hline
Variance & 132.67\\
\hline
Range & 96\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|r}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  40 & 160\\
  \hline
  \end{tabular}
  \end{table}
\end{itemize}

\newpage

\hypertarget{dev_bp}{%
\subsection{dev\_bp}\label{dev_bp}}

Description for dataelement `dev\_bp':

1 = Dev\_01; 2 = Dev\_02; 3 = Dev\_03; 4 = Dev\_04; 5 = Dev\_05; 6 =
Dev\_06; 7 = Dev\_07; 8 = Dev\_08; 9 = Dev\_09; 10 = Dev\_10; 11 =
Dev\_11; 12 = Dev\_12; 13 = Dev\_13; 14 = Dev\_14; 15 = Dev\_15; 16 =
Dev\_16; 17 = Dev\_17; 18 = Dev\_18; 19 = Dev\_19; 20 = Dev\_20; 21 =
Dev\_21; 22 = Dev\_22; 23 = Dev\_23; 24 = Dev\_24; 25 = Dev\_25

\hypertarget{representation-in-source-data-system-5}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-5}}

\begin{itemize}
\tightlist
\item
  Variable: dev\_bp
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: dev\_bp
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 12
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{dev\_bp} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
10 & 444 & 20.613\\
\hline
9 & 381 & 17.688\\
\hline
15 & 265 & 12.303\\
\hline
18 & 257 & 11.931\\
\hline
16 & 235 & 10.910\\
\hline
20 & 214 & 9.935\\
\hline
17 & 156 & 7.242\\
\hline
22 & 109 & 5.060\\
\hline
19 & 88 & 4.085\\
\hline
99902 & 3 & 0.139\\
\hline
7 & 1 & 0.046\\
\hline
14 & 1 & 0.046\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 '
\item
  Levels that are not conform with the value set:\\
  99902
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-5}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-5}}

\begin{itemize}
\tightlist
\item
  Variable: dev\_bp
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: dev\_bp
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 12
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{dev\_bp} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
10 & 444 & 20.613\\
\hline
9 & 381 & 17.688\\
\hline
15 & 265 & 12.303\\
\hline
18 & 257 & 11.931\\
\hline
16 & 235 & 10.910\\
\hline
20 & 214 & 9.935\\
\hline
17 & 156 & 7.242\\
\hline
22 & 109 & 5.060\\
\hline
19 & 88 & 4.085\\
\hline
99902 & 3 & 0.139\\
\hline
7 & 1 & 0.046\\
\hline
14 & 1 & 0.046\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 '
\item
  Levels that are not conform with the value set:\\
  99902
\end{itemize}

\newpage

\hypertarget{dev_length}{%
\subsection{dev\_length}\label{dev_length}}

Description for dataelement `dev\_length':

1 = Dev\_01; 2 = Dev\_02; 3 = Dev\_03; 4 = Dev\_04; 5 = Dev\_05; 6 =
Dev\_06; 7 = Dev\_07; 8 = Dev\_08; 9 = Dev\_09; 10 = Dev\_10; 11 =
Dev\_11; 12 = Dev\_12; 13 = Dev\_13; 14 = Dev\_14; 15 = Dev\_15; 16 =
Dev\_16; 17 = Dev\_17; 18 = Dev\_18; 19 = Dev\_19; 20 = Dev\_20; 21 =
Dev\_21; 22 = Dev\_22; 23 = Dev\_23; 24 = Dev\_24; 25 = Dev\_25

\hypertarget{representation-in-source-data-system-6}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-6}}

\begin{itemize}
\tightlist
\item
  Variable: dev\_length
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: dev\_length
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 4
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{dev\_length} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
3 & 1088 & 50.511\\
\hline
11 & 904 & 41.968\\
\hline
4 & 160 & 7.428\\
\hline
99902 & 2 & 0.093\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 '
\item
  Levels that are not conform with the value set:\\
  99902
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-6}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-6}}

\begin{itemize}
\tightlist
\item
  Variable: dev\_length
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: dev\_length
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 4
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{dev\_length} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
3 & 1088 & 50.511\\
\hline
11 & 904 & 41.968\\
\hline
4 & 160 & 7.428\\
\hline
99902 & 2 & 0.093\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 '
\item
  Levels that are not conform with the value set:\\
  99902
\end{itemize}

\newpage

\hypertarget{dev_weight}{%
\subsection{dev\_weight}\label{dev_weight}}

Description for dataelement `dev\_weight':

1 = Dev\_01; 2 = Dev\_02; 3 = Dev\_03; 4 = Dev\_04; 5 = Dev\_05; 6 =
Dev\_06; 7 = Dev\_07; 8 = Dev\_08; 9 = Dev\_09; 10 = Dev\_10; 11 =
Dev\_11; 12 = Dev\_12; 13 = Dev\_13; 14 = Dev\_14; 15 = Dev\_15; 16 =
Dev\_16; 17 = Dev\_17; 18 = Dev\_18; 19 = Dev\_19; 20 = Dev\_20; 21 =
Dev\_21; 22 = Dev\_22; 23 = Dev\_23; 24 = Dev\_24; 25 = Dev\_25

\hypertarget{representation-in-source-data-system-7}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-7}}

\begin{itemize}
\tightlist
\item
  Variable: dev\_weight
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: dev\_weight
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 4
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{dev\_weight} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
1 & 1226 & 56.917\\
\hline
11 & 904 & 41.968\\
\hline
2 & 22 & 1.021\\
\hline
99902 & 2 & 0.093\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 '
\item
  Levels that are not conform with the value set:\\
  99902
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-7}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-7}}

\begin{itemize}
\tightlist
\item
  Variable: dev\_weight
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: dev\_weight
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 4
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{dev\_weight} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
1 & 1226 & 56.917\\
\hline
11 & 904 & 41.968\\
\hline
2 & 22 & 1.021\\
\hline
99902 & 2 & 0.093\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 '
\item
  Levels that are not conform with the value set:\\
  99902
\end{itemize}

\newpage

\hypertarget{diab_age}{%
\subsection{diab\_age}\label{diab_age}}

Description for dataelement `diab\_age'

\hypertarget{representation-in-source-data-system-8}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-8}}

\begin{itemize}
\tightlist
\item
  Variable: diab\_age
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: diab\_age
\item
  Variable type: integer

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 49
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 91790.05\\
\hline
Minimum & 12\\
\hline
Median & 99801\\
\hline
Maximum & 99900\\
\hline
SD & 27115.85\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2154\\
\hline
OutLo & 173\\
\hline
OutHi & 7\\
\hline
Variance & 735269205.07\\
\hline
Range & 99888\\
\hline
\end{tabular}
\end{table}
\newpage

\hypertarget{representation-in-target-data-system-8}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-8}}

\begin{itemize}
\tightlist
\item
  Variable: diab\_age
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: diab\_age
\item
  Variable type: integer

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 49
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 91790.05\\
\hline
Minimum & 12\\
\hline
Median & 99801\\
\hline
Maximum & 99900\\
\hline
SD & 27115.85\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2154\\
\hline
OutLo & 173\\
\hline
OutHi & 7\\
\hline
Variance & 735269205.07\\
\hline
Range & 99888\\
\hline
\end{tabular}
\end{table}
\newpage

\hypertarget{diab_known}{%
\subsection{diab\_known}\label{diab_known}}

Description for dataelement `diab\_known':

0 = no; 1 = yes

\hypertarget{representation-in-source-data-system-9}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-9}}

\begin{itemize}
\tightlist
\item
  Variable: diab\_known
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: diab\_known
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 3
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{diab\_known} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
0 & 1946 & 90.344\\
\hline
1 & 201 & 9.331\\
\hline
99900 & 7 & 0.325\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 0, 1 '
\item
  Levels that are not conform with the value set:\\
  99900
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-9}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-9}}

\begin{itemize}
\tightlist
\item
  Variable: diab\_known
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: diab\_known
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 3
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{diab\_known} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
0 & 1946 & 90.344\\
\hline
1 & 201 & 9.331\\
\hline
99900 & 7 & 0.325\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 0, 1 '
\item
  Levels that are not conform with the value set:\\
  99900
\end{itemize}

\newpage

\hypertarget{exdate}{%
\subsection{exdate}\label{exdate}}

Description for dataelement `exdate'

\hypertarget{representation-in-source-data-system-10}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-10}}

\begin{itemize}
\tightlist
\item
  Variable: exdate
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: exdate
\item
  Variable type: datetime

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 688
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Min. & 1997-10-16\\
\hline
1st Qu. & 1998-08-18\\
\hline
Median & 1999-03-26\\
\hline
Mean & 1999-04-07\\
\hline
3rd Qu. & 1999-11-04\\
\hline
Max. & 2001-05-19\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules: `No future dates allowed.'
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-10}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-10}}

\begin{itemize}
\tightlist
\item
  Variable: exdate
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: exdate
\item
  Variable type: datetime

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 688
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Min. & 1997-10-16\\
\hline
1st Qu. & 1998-08-18\\
\hline
Median & 1999-03-26\\
\hline
Mean & 1999-04-07\\
\hline
3rd Qu. & 1999-11-04\\
\hline
Max. & 2001-05-19\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules: `No future dates allowed.'
\end{itemize}

\newpage

\hypertarget{family}{%
\subsection{family}\label{family}}

Description for dataelement `family':

1 = married; 2 = married (living apart); 3 = single (never married); 4 =
divorced; 5 = widowed

\hypertarget{representation-in-source-data-system-11}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-11}}

\begin{itemize}
\tightlist
\item
  Variable: family
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: family
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 7
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{family} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
1 & 1352 & 62.767\\
\hline
3 & 394 & 18.292\\
\hline
5 & 161 & 7.474\\
\hline
4 & 147 & 6.825\\
\hline
99914 & 60 & 2.786\\
\hline
2 & 33 & 1.532\\
\hline
99900 & 7 & 0.325\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2, 3, 4, 5 '
\item
  Levels that are not conform with the value set:\\
  99900\\
  99914
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-11}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-11}}

\begin{itemize}
\tightlist
\item
  Variable: family
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: family
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 7
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{family} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
1 & 1352 & 62.767\\
\hline
3 & 394 & 18.292\\
\hline
5 & 161 & 7.474\\
\hline
4 & 147 & 6.825\\
\hline
99914 & 60 & 2.786\\
\hline
2 & 33 & 1.532\\
\hline
99900 & 7 & 0.325\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2, 3, 4, 5 '
\item
  Levels that are not conform with the value set:\\
  99900\\
  99914
\end{itemize}

\newpage

\hypertarget{hdl}{%
\subsection{hdl}\label{hdl}}

Description for dataelement `hdl'

\hypertarget{representation-in-source-data-system-12}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-12}}

\begin{itemize}
\tightlist
\item
  Variable: hdl
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: hdl
\item
  Variable type: float

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2138
  \item
    Missing values: 16
  \item
    Distinct values: 1111
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 1.45\\
\hline
Minimum & 0.42\\
\hline
Median & 1.39\\
\hline
Maximum & 7.2\\
\hline
SD & 0.44\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2138\\
\hline
OutLo & 0\\
\hline
OutHi & 33\\
\hline
Variance & 0.19\\
\hline
Range & 6.78\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|l}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  0 & Inf\\
  \hline
  \end{tabular}
  \end{table}
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-12}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-12}}

\begin{itemize}
\tightlist
\item
  Variable: hdl
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: hdl
\item
  Variable type: float

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2138
  \item
    Missing values: 16
  \item
    Distinct values: 1111
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 1.45\\
\hline
Minimum & 0.42\\
\hline
Median & 1.39\\
\hline
Maximum & 7.2\\
\hline
SD & 0.44\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2138\\
\hline
OutLo & 0\\
\hline
OutHi & 33\\
\hline
Variance & 0.19\\
\hline
Range & 6.78\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|l}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  0 & Inf\\
  \hline
  \end{tabular}
  \end{table}
\end{itemize}

\newpage

\hypertarget{height}{%
\subsection{height}\label{height}}

Description for dataelement `height'

\hypertarget{representation-in-source-data-system-13}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-13}}

\begin{itemize}
\tightlist
\item
  Variable: height
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: height
\item
  Variable type: integer

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2151
  \item
    Missing values: 3
  \item
    Distinct values: 52
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 168.22\\
\hline
Minimum & 144\\
\hline
Median & 168\\
\hline
Maximum & 198\\
\hline
SD & 9.25\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2151\\
\hline
OutLo & 0\\
\hline
OutHi & 1\\
\hline
Variance & 85.48\\
\hline
Range & 54\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|r}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  80 & 230\\
  \hline
  \end{tabular}
  \end{table}
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-13}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-13}}

\begin{itemize}
\tightlist
\item
  Variable: height
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: height
\item
  Variable type: integer

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2151
  \item
    Missing values: 3
  \item
    Distinct values: 52
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 168.22\\
\hline
Minimum & 144\\
\hline
Median & 168\\
\hline
Maximum & 198\\
\hline
SD & 9.25\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2151\\
\hline
OutLo & 0\\
\hline
OutHi & 1\\
\hline
Variance & 85.48\\
\hline
Range & 54\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|r}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  80 & 230\\
  \hline
  \end{tabular}
  \end{table}
\end{itemize}

\newpage

\hypertarget{id}{%
\subsection{id}\label{id}}

Description for dataelement `id'

\hypertarget{representation-in-source-data-system-14}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-14}}

\begin{itemize}
\tightlist
\item
  Variable: id
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: id
\item
  Variable type: string

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 2154
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{id} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
3861 & 1 & 0.046\\
\hline
6506 & 1 & 0.046\\
\hline
6096 & 1 & 0.046\\
\hline
6674 & 1 & 0.046\\
\hline
6490 & 1 & 0.046\\
\hline
5366 & 1 & 0.046\\
\hline
5735 & 1 & 0.046\\
\hline
4031 & 1 & 0.046\\
\hline
3578 & 1 & 0.046\\
\hline
4807 & 1 & 0.046\\
\hline
5450 & 1 & 0.046\\
\hline
4763 & 1 & 0.046\\
\hline
4146 & 1 & 0.046\\
\hline
7096 & 1 & 0.046\\
\hline
3726 & 1 & 0.046\\
\hline
5459 & 1 & 0.046\\
\hline
5161 & 1 & 0.046\\
\hline
5562 & 1 & 0.046\\
\hline
4111 & 1 & 0.046\\
\hline
6392 & 1 & 0.046\\
\hline
5553 & 1 & 0.046\\
\hline
5404 & 1 & 0.046\\
\hline
3673 & 1 & 0.046\\
\hline
6808 & 1 & 0.046\\
\hline
5760 & 1 & 0.046\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules: ' \footnote{{[}:digit:{]}}\{1,5\}\$ '
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-14}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-14}}

\begin{itemize}
\tightlist
\item
  Variable: id
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: id
\item
  Variable type: string

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 2154
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{id} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
3861 & 1 & 0.046\\
\hline
6506 & 1 & 0.046\\
\hline
6096 & 1 & 0.046\\
\hline
6674 & 1 & 0.046\\
\hline
6490 & 1 & 0.046\\
\hline
5366 & 1 & 0.046\\
\hline
5735 & 1 & 0.046\\
\hline
4031 & 1 & 0.046\\
\hline
3578 & 1 & 0.046\\
\hline
4807 & 1 & 0.046\\
\hline
5450 & 1 & 0.046\\
\hline
4763 & 1 & 0.046\\
\hline
4146 & 1 & 0.046\\
\hline
7096 & 1 & 0.046\\
\hline
3726 & 1 & 0.046\\
\hline
5459 & 1 & 0.046\\
\hline
5161 & 1 & 0.046\\
\hline
5562 & 1 & 0.046\\
\hline
4111 & 1 & 0.046\\
\hline
6392 & 1 & 0.046\\
\hline
5553 & 1 & 0.046\\
\hline
5404 & 1 & 0.046\\
\hline
3673 & 1 & 0.046\\
\hline
6808 & 1 & 0.046\\
\hline
5760 & 1 & 0.046\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules: ' \footnote{{[}:digit:{]}}\{1,5\}\$ '
\end{itemize}

\newpage

\hypertarget{income}{%
\subsection{income}\label{income}}

Description for dataelement `income':

1 = \textless{} 2000; 2 = 2000 ï¿½ 4000; 3 = \textgreater{} 4000

\hypertarget{representation-in-source-data-system-15}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-15}}

\begin{itemize}
\tightlist
\item
  Variable: income
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: income
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 5
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{income} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
2 & 992 & 46.054\\
\hline
1 & 602 & 27.948\\
\hline
3 & 444 & 20.613\\
\hline
99901 & 100 & 4.643\\
\hline
99900 & 16 & 0.743\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2, 3 '
\item
  Levels that are not conform with the value set:\\
  99900\\
  99901
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-15}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-15}}

\begin{itemize}
\tightlist
\item
  Variable: income
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: income
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 5
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{income} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
2 & 992 & 46.054\\
\hline
1 & 602 & 27.948\\
\hline
3 & 444 & 20.613\\
\hline
99901 & 100 & 4.643\\
\hline
99900 & 16 & 0.743\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2, 3 '
\item
  Levels that are not conform with the value set:\\
  99900\\
  99901
\end{itemize}

\newpage

\hypertarget{ldl}{%
\subsection{ldl}\label{ldl}}

Description for dataelement `ldl'

\hypertarget{representation-in-source-data-system-16}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-16}}

\begin{itemize}
\tightlist
\item
  Variable: ldl
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: ldl
\item
  Variable type: float

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2126
  \item
    Missing values: 28
  \item
    Distinct values: 2125
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 3.58\\
\hline
Minimum & 0.7\\
\hline
Median & 3.52\\
\hline
Maximum & 9.24\\
\hline
SD & 1.13\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2126\\
\hline
OutLo & 0\\
\hline
OutHi & 21\\
\hline
Variance & 1.28\\
\hline
Range & 8.54\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|l}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  0 & Inf\\
  \hline
  \end{tabular}
  \end{table}
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-16}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-16}}

\begin{itemize}
\tightlist
\item
  Variable: ldl
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: ldl
\item
  Variable type: float

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2126
  \item
    Missing values: 28
  \item
    Distinct values: 2125
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 3.58\\
\hline
Minimum & 0.7\\
\hline
Median & 3.52\\
\hline
Maximum & 9.24\\
\hline
SD & 1.13\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2126\\
\hline
OutLo & 0\\
\hline
OutHi & 21\\
\hline
Variance & 1.28\\
\hline
Range & 8.54\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|l}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  0 & Inf\\
  \hline
  \end{tabular}
  \end{table}
\end{itemize}

\newpage

\hypertarget{myocard}{%
\subsection{myocard}\label{myocard}}

Description for dataelement `myocard':

1 = yes; 2 = no

\hypertarget{representation-in-source-data-system-17}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-17}}

\begin{itemize}
\tightlist
\item
  Variable: myocard
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: myocard
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 5
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{myocard} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
2 & 2015 & 93.547\\
\hline
1 & 65 & 3.018\\
\hline
99914 & 60 & 2.786\\
\hline
99901 & 7 & 0.325\\
\hline
99900 & 7 & 0.325\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2 '
\item
  Levels that are not conform with the value set:\\
  99900\\
  99901\\
  99914
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-17}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-17}}

\begin{itemize}
\tightlist
\item
  Variable: myocard
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: myocard
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 5
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{myocard} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
2 & 2015 & 93.547\\
\hline
1 & 65 & 3.018\\
\hline
99914 & 60 & 2.786\\
\hline
99901 & 7 & 0.325\\
\hline
99900 & 7 & 0.325\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2 '
\item
  Levels that are not conform with the value set:\\
  99900\\
  99901\\
  99914
\end{itemize}

\newpage

\hypertarget{obs_bp}{%
\subsection{obs\_bp}\label{obs_bp}}

Description for dataelement `obs\_bp':

1 = Obs\_01; 2 = Obs\_02; 3 = Obs\_03; 4 = Obs\_04; 5 = Obs\_05; 6 =
Obs\_06; 7 = Obs\_07; 8 = Obs\_08; 9 = Obs\_09; 10 = Obs\_10; 11 =
Obs\_11; 12 = Obs\_12; 13 = Obs\_13; 14 = Obs\_14; 15 = Obs\_15; 16 =
Obs\_16; 17 = Obs\_17; 18 = Obs\_18; 19 = Obs\_19; 20 = Obs\_20

\hypertarget{representation-in-source-data-system-18}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-18}}

\begin{itemize}
\tightlist
\item
  Variable: obs\_bp
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: obs\_bp
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 11
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{obs\_bp} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
4 & 763 & 35.422\\
\hline
7 & 477 & 22.145\\
\hline
9 & 384 & 17.827\\
\hline
3 & 330 & 15.320\\
\hline
5 & 149 & 6.917\\
\hline
8 & 41 & 1.903\\
\hline
1 & 4 & 0.186\\
\hline
99902 & 3 & 0.139\\
\hline
11 & 1 & 0.046\\
\hline
18 & 1 & 0.046\\
\hline
16 & 1 & 0.046\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 20 '
\item
  Levels that are not conform with the value set:\\
  99902
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-18}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-18}}

\begin{itemize}
\tightlist
\item
  Variable: obs\_bp
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: obs\_bp
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 11
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{obs\_bp} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
4 & 763 & 35.422\\
\hline
7 & 477 & 22.145\\
\hline
9 & 384 & 17.827\\
\hline
3 & 330 & 15.320\\
\hline
5 & 149 & 6.917\\
\hline
8 & 41 & 1.903\\
\hline
1 & 4 & 0.186\\
\hline
99902 & 3 & 0.139\\
\hline
11 & 1 & 0.046\\
\hline
18 & 1 & 0.046\\
\hline
16 & 1 & 0.046\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 20 '
\item
  Levels that are not conform with the value set:\\
  99902
\end{itemize}

\newpage

\hypertarget{obs_int}{%
\subsection{obs\_int}\label{obs_int}}

Description for dataelement `obs\_int':

1 = Obs\_01; 2 = Obs\_02; 3 = Obs\_03; 4 = Obs\_04; 5 = Obs\_05; 6 =
Obs\_06; 7 = Obs\_07; 8 = Obs\_08; 9 = Obs\_09; 10 = Obs\_10; 11 =
Obs\_11; 12 = Obs\_12; 13 = Obs\_13; 14 = Obs\_14; 15 = Obs\_15; 16 =
Obs\_16; 17 = Obs\_17; 18 = Obs\_18; 19 = Obs\_19; 20 = Obs\_20 ; 21 =
Obs\_21; 22 = Obs\_22; 23 = Obs\_23; 24 = Obs\_24; 25 = Obs\_25

\hypertarget{representation-in-source-data-system-19}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-19}}

\begin{itemize}
\tightlist
\item
  Variable: obs\_int
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: obs\_int
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 14
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{obs\_int} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
2 & 600 & 27.855\\
\hline
1 & 396 & 18.384\\
\hline
11 & 349 & 16.202\\
\hline
22 & 277 & 12.860\\
\hline
3 & 235 & 10.910\\
\hline
12 & 122 & 5.664\\
\hline
10 & 78 & 3.621\\
\hline
23 & 67 & 3.110\\
\hline
4 & 11 & 0.511\\
\hline
5 & 11 & 0.511\\
\hline
7 & 5 & 0.232\\
\hline
99900 & 1 & 0.046\\
\hline
25 & 1 & 0.046\\
\hline
13 & 1 & 0.046\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 '
\item
  Levels that are not conform with the value set:\\
  99900
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-19}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-19}}

\begin{itemize}
\tightlist
\item
  Variable: obs\_int
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: obs\_int
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 14
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{obs\_int} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
2 & 600 & 27.855\\
\hline
1 & 396 & 18.384\\
\hline
11 & 349 & 16.202\\
\hline
22 & 277 & 12.860\\
\hline
3 & 235 & 10.910\\
\hline
12 & 122 & 5.664\\
\hline
10 & 78 & 3.621\\
\hline
23 & 67 & 3.110\\
\hline
4 & 11 & 0.511\\
\hline
5 & 11 & 0.511\\
\hline
7 & 5 & 0.232\\
\hline
99900 & 1 & 0.046\\
\hline
25 & 1 & 0.046\\
\hline
13 & 1 & 0.046\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 '
\item
  Levels that are not conform with the value set:\\
  99900
\end{itemize}

\newpage

\hypertarget{obs_soma}{%
\subsection{obs\_soma}\label{obs_soma}}

Description for dataelement `obs\_soma':

1 = Obs\_01; 2 = Obs\_02; 3 = Obs\_03; 4 = Obs\_04; 5 = Obs\_05; 6 =
Obs\_06; 7 = Obs\_07; 8 = Obs\_08; 9 = Obs\_09; 10 = Obs\_10

\hypertarget{representation-in-source-data-system-20}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-20}}

\begin{itemize}
\tightlist
\item
  Variable: obs\_soma
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: obs\_soma
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 9
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{obs\_soma} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
4 & 645 & 29.944\\
\hline
7 & 483 & 22.423\\
\hline
9 & 388 & 18.013\\
\hline
5 & 320 & 14.856\\
\hline
3 & 280 & 12.999\\
\hline
8 & 31 & 1.439\\
\hline
1 & 3 & 0.139\\
\hline
2 & 2 & 0.093\\
\hline
99902 & 2 & 0.093\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 '
\item
  Levels that are not conform with the value set:\\
  99902
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-20}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-20}}

\begin{itemize}
\tightlist
\item
  Variable: obs\_soma
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: obs\_soma
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 9
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{obs\_soma} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
4 & 645 & 29.944\\
\hline
7 & 483 & 22.423\\
\hline
9 & 388 & 18.013\\
\hline
5 & 320 & 14.856\\
\hline
3 & 280 & 12.999\\
\hline
8 & 31 & 1.439\\
\hline
1 & 3 & 0.139\\
\hline
2 & 2 & 0.093\\
\hline
99902 & 2 & 0.093\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 '
\item
  Levels that are not conform with the value set:\\
  99902
\end{itemize}

\newpage

\hypertarget{sbp1}{%
\subsection{sbp1}\label{sbp1}}

Description for dataelement `sbp1'

\hypertarget{representation-in-source-data-system-21}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-21}}

\begin{itemize}
\tightlist
\item
  Variable: sbp1
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: sbp1
\item
  Variable type: integer

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2152
  \item
    Missing values: 2
  \item
    Distinct values: 125
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 139.01\\
\hline
Minimum & 83\\
\hline
Median & 137\\
\hline
Maximum & 253\\
\hline
SD & 22.5\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2152\\
\hline
OutLo & 0\\
\hline
OutHi & 23\\
\hline
Variance & 506.09\\
\hline
Range & 170\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|r}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  80 & 200\\
  \hline
  \end{tabular}
  \end{table}
\item
  Extrem values are not conform with constraints.
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-21}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-21}}

\begin{itemize}
\tightlist
\item
  Variable: sbp1
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: sbp1
\item
  Variable type: integer

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2152
  \item
    Missing values: 2
  \item
    Distinct values: 125
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 139.01\\
\hline
Minimum & 83\\
\hline
Median & 137\\
\hline
Maximum & 253\\
\hline
SD & 22.5\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2152\\
\hline
OutLo & 0\\
\hline
OutHi & 23\\
\hline
Variance & 506.09\\
\hline
Range & 170\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|r}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  80 & 200\\
  \hline
  \end{tabular}
  \end{table}
\item
  Extrem values are not conform with constraints.
\end{itemize}

\newpage

\hypertarget{sbp2}{%
\subsection{sbp2}\label{sbp2}}

Description for dataelement `sbp2'

\hypertarget{representation-in-source-data-system-22}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-22}}

\begin{itemize}
\tightlist
\item
  Variable: sbp2
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: sbp2
\item
  Variable type: integer

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2148
  \item
    Missing values: 6
  \item
    Distinct values: 123
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 136.4\\
\hline
Minimum & 83\\
\hline
Median & 134\\
\hline
Maximum & 258\\
\hline
SD & 21.86\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2148\\
\hline
OutLo & 0\\
\hline
OutHi & 24\\
\hline
Variance & 477.76\\
\hline
Range & 175\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|r}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  80 & 200\\
  \hline
  \end{tabular}
  \end{table}
\item
  Extrem values are not conform with constraints.
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-22}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-22}}

\begin{itemize}
\tightlist
\item
  Variable: sbp2
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: sbp2
\item
  Variable type: integer

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2148
  \item
    Missing values: 6
  \item
    Distinct values: 123
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 136.4\\
\hline
Minimum & 83\\
\hline
Median & 134\\
\hline
Maximum & 258\\
\hline
SD & 21.86\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2148\\
\hline
OutLo & 0\\
\hline
OutHi & 24\\
\hline
Variance & 477.76\\
\hline
Range & 175\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|r}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  80 & 200\\
  \hline
  \end{tabular}
  \end{table}
\item
  Extrem values are not conform with constraints.
\end{itemize}

\newpage

\hypertarget{school}{%
\subsection{school}\label{school}}

Description for dataelement `school':

0 = none; 1 = lower secondary; 2 = secondary; 3 = upper secondary

\hypertarget{representation-in-source-data-system-23}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-23}}

\begin{itemize}
\tightlist
\item
  Variable: school
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: school
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 7
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{school} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
2 & 981 & 45.543\\
\hline
0 & 779 & 36.165\\
\hline
1 & 256 & 11.885\\
\hline
99914 & 60 & 2.786\\
\hline
99900 & 53 & 2.461\\
\hline
3 & 18 & 0.836\\
\hline
4 & 7 & 0.325\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 0, 1, 2, 3 '
\item
  Levels that are not conform with the value set:\\
  4\\
  99900\\
  99914
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-23}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-23}}

\begin{itemize}
\tightlist
\item
  Variable: school
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: school
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 7
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{school} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
2 & 981 & 45.543\\
\hline
0 & 779 & 36.165\\
\hline
1 & 256 & 11.885\\
\hline
99914 & 60 & 2.786\\
\hline
99900 & 53 & 2.461\\
\hline
3 & 18 & 0.836\\
\hline
4 & 7 & 0.325\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 0, 1, 2, 3 '
\item
  Levels that are not conform with the value set:\\
  4\\
  99900\\
  99914
\end{itemize}

\newpage

\hypertarget{sex}{%
\subsection{sex}\label{sex}}

Description for dataelement `sex':

1 = males; 2 = females

\hypertarget{representation-in-source-data-system-24}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-24}}

\begin{itemize}
\tightlist
\item
  Variable: sex
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: sex
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 2
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{sex} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
2 & 1167 & 54.178\\
\hline
1 & 987 & 45.822\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules: ' 1, 2 '
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-24}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-24}}

\begin{itemize}
\tightlist
\item
  Variable: sex
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: sex
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 2
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{sex} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
2 & 1167 & 54.178\\
\hline
1 & 987 & 45.822\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules: ' 1, 2 '
\end{itemize}

\newpage

\hypertarget{smoking}{%
\subsection{smoking}\label{smoking}}

Description for dataelement `smoking':

0 = nonsmoker; 1 = former smoker; 2 = smoker

\hypertarget{representation-in-source-data-system-25}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-25}}

\begin{itemize}
\tightlist
\item
  Variable: smoking
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: smoking
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 5
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{smoking} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
0 & 733 & 34.030\\
\hline
1 & 697 & 32.358\\
\hline
2 & 656 & 30.455\\
\hline
99914 & 60 & 2.786\\
\hline
99900 & 8 & 0.371\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 0, 1, 2 '
\item
  Levels that are not conform with the value set:\\
  99900\\
  99914
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-25}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-25}}

\begin{itemize}
\tightlist
\item
  Variable: smoking
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: smoking
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 5
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{smoking} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
0 & 733 & 34.030\\
\hline
1 & 697 & 32.358\\
\hline
2 & 656 & 30.455\\
\hline
99914 & 60 & 2.786\\
\hline
99900 & 8 & 0.371\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 0, 1, 2 '
\item
  Levels that are not conform with the value set:\\
  99900\\
  99914
\end{itemize}

\newpage

\hypertarget{stroke}{%
\subsection{stroke}\label{stroke}}

Description for dataelement `stroke':

1 = yes; 2 = no

\hypertarget{representation-in-source-data-system-26}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-26}}

\begin{itemize}
\tightlist
\item
  Variable: stroke
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: stroke
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 5
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{stroke} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
2 & 2028 & 94.150\\
\hline
99914 & 60 & 2.786\\
\hline
1 & 56 & 2.600\\
\hline
99900 & 7 & 0.325\\
\hline
99901 & 3 & 0.139\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2 '
\item
  Levels that are not conform with the value set:\\
  99900\\
  99901\\
  99914
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-26}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-26}}

\begin{itemize}
\tightlist
\item
  Variable: stroke
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: stroke
\item
  Variable type: enumerated

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2154
  \item
    Missing values: 0
  \item
    Distinct values: 5
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{stroke} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
2 & 2028 & 94.150\\
\hline
99914 & 60 & 2.786\\
\hline
1 & 56 & 2.600\\
\hline
99900 & 7 & 0.325\\
\hline
99901 & 3 & 0.139\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1, 2 '
\item
  Levels that are not conform with the value set:\\
  99900\\
  99901\\
  99914
\end{itemize}

\newpage

\hypertarget{waist}{%
\subsection{waist}\label{waist}}

Description for dataelement `waist'

\hypertarget{representation-in-source-data-system-27}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-27}}

\begin{itemize}
\tightlist
\item
  Variable: waist
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: waist
\item
  Variable type: float

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2148
  \item
    Missing values: 6
  \item
    Distinct values: 2102
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 89.21\\
\hline
Minimum & 49.27\\
\hline
Median & 89.52\\
\hline
Maximum & 145.77\\
\hline
SD & 13.82\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2148\\
\hline
OutLo & 0\\
\hline
OutHi & 6\\
\hline
Variance & 191.09\\
\hline
Range & 96.5\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|l}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  30 & Inf\\
  \hline
  \end{tabular}
  \end{table}
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-27}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-27}}

\begin{itemize}
\tightlist
\item
  Variable: waist
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: waist
\item
  Variable type: float

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2148
  \item
    Missing values: 6
  \item
    Distinct values: 2102
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 89.21\\
\hline
Minimum & 49.27\\
\hline
Median & 89.52\\
\hline
Maximum & 145.77\\
\hline
SD & 13.82\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2148\\
\hline
OutLo & 0\\
\hline
OutHi & 6\\
\hline
Variance & 191.09\\
\hline
Range & 96.5\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|l}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  30 & Inf\\
  \hline
  \end{tabular}
  \end{table}
\end{itemize}

\newpage

\hypertarget{weight}{%
\subsection{weight}\label{weight}}

Description for dataelement `weight'

\hypertarget{representation-in-source-data-system-28}{%
\subsubsection{\texorpdfstring{Representation in \textbf{source} data
system}{Representation in source data system}}\label{representation-in-source-data-system-28}}

\begin{itemize}
\tightlist
\item
  Variable: weight
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: weight
\item
  Variable type: float

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2150
  \item
    Missing values: 4
  \item
    Distinct values: 1763
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 77.63\\
\hline
Minimum & 42.6\\
\hline
Median & 77.04\\
\hline
Maximum & 144.44\\
\hline
SD & 15.08\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2150\\
\hline
OutLo & 0\\
\hline
OutHi & 17\\
\hline
Variance & 227.34\\
\hline
Range & 101.84\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|r}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  30 & 250\\
  \hline
  \end{tabular}
  \end{table}
\end{itemize}

\newpage

\hypertarget{representation-in-target-data-system-28}{%
\subsubsection{\texorpdfstring{Representation in \textbf{target} data
system}{Representation in target data system}}\label{representation-in-target-data-system-28}}

\begin{itemize}
\tightlist
\item
  Variable: weight
\item
  Table: ship\_data.csv
\end{itemize}

\textbf{Overview:}

\begin{itemize}
\tightlist
\item
  Variable name: weight
\item
  Variable type: float

  \begin{itemize}
  \tightlist
  \item
    n: 2154
  \item
    Valid values: 2150
  \item
    Missing values: 4
  \item
    Distinct values: 1763
  \end{itemize}
\end{itemize}

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|l}
\hline
Mean & 77.63\\
\hline
Minimum & 42.6\\
\hline
Median & 77.04\\
\hline
Maximum & 144.44\\
\hline
SD & 15.08\\
\hline
Negativ & 0\\
\hline
Zero & 0\\
\hline
Positive & 2150\\
\hline
OutLo & 0\\
\hline
OutHi & 17\\
\hline
Variance & 227.34\\
\hline
Range & 101.84\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: passed
\item
  Constraining values/rules:

  \begin{table}[H]
  \centering
  \begin{tabular}{r|r}
  \hline
  \textbf{min} & \textbf{max}\\
  \hline
  30 & 250\\
  \hline
  \end{tabular}
  \end{table}
\end{itemize}

\newpage

\hypertarget{plausibility-checks}{%
\section{Plausibility Checks}\label{plausibility-checks}}

\hypertarget{atemporal-plausibility}{%
\subsection{Atemporal Plausibility}\label{atemporal-plausibility}}

\hypertarget{a_present_and_b_vv}{%
\subsubsection{A\_present\_and\_B\_vv}\label{a_present_and_b_vv}}

Contracept in males.

\hypertarget{representation-in-source-data-system-29}{%
\paragraph{Representation in source data
system}\label{representation-in-source-data-system-29}}

\begin{itemize}
\tightlist
\item
  Variable 1: sex
\item
  Variable 2: contraception
\item
  Filter criterion variable 2 (regex): \^{}1\$
\item
  Join criterion: id
\end{itemize}

\textbf{Overview:}

No data available for reporting

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{sex} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
2 & 572 & 97.945\\
\hline
1 & 12 & 2.055\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1 '
\item
  Levels that are not conform with the value set:\\
  2
\end{itemize}

\hypertarget{representation-in-target-data-system-29}{%
\paragraph{Representation in target data
system}\label{representation-in-target-data-system-29}}

\begin{itemize}
\tightlist
\item
  Variable 1: sex
\item
  Variable 2: contraception
\item
  Filter criterion variable 2 (regex): \^{}1\$
\item
  Join criterion: id
\end{itemize}

\textbf{Overview:}

No data available for reporting

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{sex} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
2 & 572 & 97.945\\
\hline
1 & 12 & 2.055\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1 '
\item
  Levels that are not conform with the value set:\\
  2
\end{itemize}

\hypertarget{a_present_and_b_levels_vl}{%
\subsubsection{A\_present\_and\_B\_levels\_vl}\label{a_present_and_b_levels_vl}}

Diab age but no diab.

\hypertarget{representation-in-source-data-system-30}{%
\paragraph{Representation in source data
system}\label{representation-in-source-data-system-30}}

\begin{itemize}
\tightlist
\item
  Variable 1: diab\_known
\item
  Variable 2: diab\_age
\item
  Filter criterion variable 2 (regex):
  \^{}(?!.\emph{(99900\textbar99901\textbar99801)).}\$
\item
  Join criterion: id
\end{itemize}

\textbf{Overview:}

No data available for reporting

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{diab\_known} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
1 & 138 & 79.769\\
\hline
0 & 35 & 20.231\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1 '
\item
  Levels that are not conform with the value set:\\
  0
\end{itemize}

\hypertarget{representation-in-target-data-system-30}{%
\paragraph{Representation in target data
system}\label{representation-in-target-data-system-30}}

\begin{itemize}
\tightlist
\item
  Variable 1: diab\_known
\item
  Variable 2: diab\_age
\item
  Filter criterion variable 2 (regex):
  \^{}(?!.\emph{(99900\textbar99901\textbar99801)).}\$
\item
  Join criterion: id
\end{itemize}

\textbf{Overview:}

No data available for reporting

\textbf{Results:}\\

\begin{table}[H]
\centering
\begin{tabular}{l|r|r}
\hline
\textbf{diab\_known} & \textbf{Freq} & \textbf{\% Valid}\\
\hline
1 & 138 & 79.769\\
\hline
0 & 35 & 20.231\\
\hline
\end{tabular}
\end{table}

\textbf{Value conformance:}

\begin{itemize}
\tightlist
\item
  Conformance check: failed
\item
  Constraining values/rules: ' 1 '
\item
  Levels that are not conform with the value set:\\
  0
\end{itemize}

\hypertarget{uniqueness-plausibility}{%
\subsection{Uniqueness Plausibility}\label{uniqueness-plausibility}}

\hypertarget{sex-1}{%
\subsubsection{sex}\label{sex-1}}

With each distinct value of `id', only one value of `sex' may be
associated.

\hypertarget{representation-in-source-data-system-31}{%
\paragraph{Representation in source data
system}\label{representation-in-source-data-system-31}}

\begin{itemize}
\tightlist
\item
  Plausibility check: passed
\item
  Message: No duplicate occurrences of id found in association with sex.
\end{itemize}

\hypertarget{representation-in-target-data-system-31}{%
\paragraph{Representation in target data
system}\label{representation-in-target-data-system-31}}

\begin{itemize}
\tightlist
\item
  Plausibility check: passed
\item
  Message: No duplicate occurrences of id found in association with sex.
\end{itemize}

\newpage

\hypertarget{appendix}{%
\section{Appendix}\label{appendix}}

\hypertarget{r-package-version-dqastats}{%
\subsection{R-Package Version
`DQAstats'}\label{r-package-version-dqastats}}

\begin{verbatim}
## [1] '0.2.6.9003'
\end{verbatim}

\hypertarget{r-package-version-dizutils}{%
\subsection{R-Package Version
`DIZutils'}\label{r-package-version-dizutils}}

\begin{verbatim}
## [1] '0.0.15.9002'
\end{verbatim}

\hypertarget{r-package-version-diztools}{%
\subsection{R-Package Version
`DIZtools'}\label{r-package-version-diztools}}

\begin{verbatim}
## [1] '0.0.4'
\end{verbatim}

\begin{verbatim}
## 
## ## SQL Statments
\end{verbatim}

\begin{verbatim}
## 
## ### Source Data System
\end{verbatim}

\begin{verbatim}
## 
## ### Target Data System
\end{verbatim}

\end{document}
