---
title: ExPanD - Explore your data!
output: html_notebook
---
 
 
### Setup
 
```{r setup}
suppressWarnings(suppressMessages({
  library(knitr)
  library(kableExtra)
  library(htmltools)
  library(tidyverse)
  library(scales)
  library(ExPanDaR)
}))
knitr::opts_chunk$set(fig.align = 'center')
```
 
 
### Create Sample
 
This step reads the raw data provided by `ExPanD()` and generates the sample for the analysis.
 
```{r create_sample}
create_sample <- function(df, df_def) {
  # Set infinite numerical variables to NA
  df[, df_def$var_name[df_def$type == "numeric"]] <-
    lapply(df[, df_def$var_name[df_def$type == "numeric"]],
      function(x) ifelse(is.finite(x), x, NA))
 
  # Delete numerical variables that only contain NAs
  all_na_vars <- sapply(df, function (x) all(is.na(x)))
  df_def <- df_def[!all_na_vars,]
  df <- df[, df_def$var_name]
 
  # Drop observations that are NA in variables that are not allowed to
  df <- df[complete.cases(df[, df_def$var_name[which(df_def$can_be_na == FALSE)]]), ]
 
  df <- droplevels(df)
  return(list(df = df, df_def = df_def))
}
 
load("ExPanD_nb_data.Rdata")
 
smp_list <- create_sample(nb_df, nb_df_def)
smp <- smp_list$df
smp_def <- smp_list$df_def
```
 
 
### Bar Chart
 
```{r bar_chart}
df <- smp
df$myocard <- as.factor(df$myocard)
df$sex <- as.factor(df$sex)
p <- ggplot(df, aes(x = myocard)) +
  geom_bar(aes(fill= sex), position = "stack") +
  labs(x = "myocard", fill = "sex")
p
```
 
 
### Descriptive Statistics
 
```{r descriptive_statistics}
df <- smp
t <- prepare_descriptive_table(smp)
t$kable_ret  %>%
  kable_styling("condensed", full_width = F, position = "center")
```
 
 
### Histogram
 
```{r histogram}
var <- as.numeric(smp$age)
hist(var, main="", xlab = "age", col="red", right = FALSE, breaks= 20)
```
 
 
### Extreme Observations
 
```{r extreme_obs}
df <- smp
vars <- c("cs_id", "sbp1")
df <- df[, vars]
df <- droplevels(df[complete.cases(df), ])
if (nrow(df) <= 10) {
  cat("Not enough data to generate table")
} else {
  tab <- prepare_ext_obs_table(df, var = "sbp1")
  tab$kable_ret %>%
    kable_styling()
}
```
 
 
### By Group Bar Graph
 
```{r by_group_bar_graph}
df <- smp
prepare_by_group_bar_graph(df, "school", "income", mean, TRUE)$plot +
  ylab("mean income")
```
 
 
### By Group Violin Graph
 
```{r by_group_violin_graph}
df <- smp
prepare_by_group_violin_graph(df, "sex", "sbp1", TRUE)
```
 
 
### Correlation Graph
 
```{r corrplot}
df <- smp
ret <- prepare_correlation_graph(df[, c(1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29)])
```
 
 
### Scatter Plot
 
```{r scatter_plot}
df <- smp
df <- df[, c("cs_id", "ts_id", "weight", "height", "sex", "cholesterol")]
df <- df[complete.cases(df), ]
df$sex <- as.factor(df$sex)
set.seed(42)
df <- sample_n(df, 1000)
prepare_scatter_plot(df, "weight", "height", color = "sex", size = "cholesterol", loess = 1)
```
 
 
### Regresssion Table
 
```{r regression}
df <- smp
df <- df[, c("cholesterol", "age", "weight")]
df <- df[complete.cases(df), ]
df <- droplevels(df)
t <- prepare_regression_table(df, dvs = "cholesterol", idvs = c("age", "weight"), models = "ols")
HTML(t$table)
```
 
 
### Note
 
This Notebook has been automatically generated using the [ExPanDaR](https://joachim-gassen.github.io/ExPanDaR) package.
 
